"""
Core configuration and constants.
"""
from pathlib import Path

ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"
DB_PATH = ROOT / "prices.db"

LEAGUE = "Runes of Aldur"
TRADE_BASE = "https://www.pathofexile.com"
USER_AGENT = "OAuth poe2ninja-tool/1.0 (contact: dev@example.com)"

DEFAULT_HOTKEY = "ctrl_c"

RARITY_MAP = {
    "NORMAL": "normal",
    "MAGIC": "magic",
    "RARE": "rare",
    "UNIQUE": "unique",
    "GEM": "gem",
    "CURRENCY": "currency",
    "DIVINATION": "divcard",
    "DIVINATION CARD": "divcard",
    "QUEST": "quest",
}

CATEGORY_TO_TRADE_ID = {
    "amulet": "accessory.amulet",
    "belt": "accessory.belt",
    "ring": "accessory.ring",
    "body armour": "armour.chest",
    "body armours": "armour.chest",
    "boots": "armour.boots",
    "gloves": "armour.gloves",
    "helmet": "armour.helmet",
    "helmets": "armour.helmet",
    "shield": "armour.shield",
    "shields": "armour.shield",
    "quiver": "armour.quiver",
    "focus": "armour.focus",
    "buckler": "armour.buckler",
    "bow": "weapon.bow",
    "crossbow": "weapon.crossbow",
    "dagger": "weapon.dagger",
    "one-handed axe": "weapon.oneaxe",
    "one-handed mace": "weapon.onemace",
    "one-handed sword": "weapon.onesword",
    "two-handed axe": "weapon.twoaxe",
    "two-handed mace": "weapon.twomace",
    "two-handed sword": "weapon.twosword",
    "wand": "weapon.wand",
    "staff": "weapon.staff",
    "warstaff": "weapon.warstaff",
    "spear": "weapon.spear",
    "flail": "weapon.flail",
    "claw": "weapon.claw",
    "sceptre": "weapon.sceptre",
    "rune dagger": "weapon.runedagger",
    "fishing rod": "weapon.rod",
    "flask": "flask",
    "life flask": "flask",
    "mana flask": "flask",
    "charm": "flask.charm",
    "talisman": "weapon.talisman",
    "tincture": "tincture",
    "jewel": "jewel",
    "cluster jewel": "jewel.cluster",
    "waystone": "map.waystone",
    "map": "map",
    "tablet": "map.tablet",
    "map fragment": "map.fragment",
    "skill gem": "gem.activegem",
    "support gem": "gem.supportgem",
    "meta gem": "gem.metagem",
    "soul core": "soulcore",
    "rune": "rune",
}

CURRENCY_TAGS = {
    "chaos": "chaos",
    "divine": "divine",
    "exalted": "exalted",
    "exalted orb": "exalted",
    "divine orb": "divine",
    "chaos orb": "chaos",
    "perfect exalted orb": "perfect-exalted-orb",
    "perfect chaos orb": "perfect-chaos-orb",
    "greater exalted orb": "greater-exalted-orb",
    "greater chaos orb": "greater-chaos-orb",
    "regal": "regal",
    "regal orb": "regal",
    "orb of alchemy": "alch",
    "alchemy": "alch",
    "orb of augmentation": "aug",
    "augmentation": "aug",
    "orb of transmutation": "transmute",
    "transmutation": "transmute",
    "orb of chance": "chance",
    "chance": "chance",
    "chromatic": "chromatic",
    "chromatic orb": "chromatic",
    "jeweller": "jeweller",
    "jeweller's orb": "jeweller",
    "fusing": "fusing",
    "orb of fusing": "fusing",
    "scouring": "scour",
    "orb of scouring": "scour",
    "regret": "regret",
    "orb of regret": "regret",
    "blessed": "blessed",
    "orb of alchemy": "alch",
    "vaal": "vaal",
    "annul": "annul",
    "annulment": "annul",
    "orb of annulment": "annul",
    "perfect": "perfect",
    "greater": "greater",
    "mirror": "mirror",
    "mirror of kalandra": "mirror",
    "gemcutter": "gcp",
    "gemcutter's prism": "gcp",
    "cartographer": "chisel",
    "cartographer's chisel": "chisel",
    "arcanist": "arcanist",
    "arcanist's etching": "arcanist",
    "engineer's": "engineers-orb",
    "engineer's orb": "engineers-orb",
    "artificer's": "artificers-orb",
    "artificer's orb": "artificers-orb",
    "shaper's": "shaper-orb",
    "elder's": "elder-orb",
    "ancient": "ancient-orb",
    "orb of horizons": "horizon",
    "horizon": "horizon",
    "harbinger": "harbinger-orb",
    "stack of deck": "deck",
    "divination": "divcard",
}

ITEM_TYPES_FOR_CURRENCY_TRADE = {
    "Currency": "currency",
    "Divination Card": "divcard",
    "Fragment": "fragment",
    "Map Fragment": "fragment",
    "Essence": "essence",
    "Fossil": "fossil",
    "Resonator": "resonator",
    "Oil": "oil",
    "Incubator": "incubator",
    "Scarab": "scarab",
    "Omen": "omen",
    "Waystone": "waystone",
    "Map": "map",
    "Tablet": "tablet",
    "Flask": "flask",
    "Charm": "charm",
    "Soul Core": "soulcore",
    "Rune": "rune",
    "Unique": "unique",
    "Skill Gem": "gem",
    "Support Gem": "gem",
    "Meta Gem": "gem",
    "Jewel": "jewel",
    "Cluster Jewel": "jewel",
    "Amulet": "accessory",
    "Ring": "accessory",
    "Belt": "accessory",
    "Helmet": "armour",
    "Body Armour": "armour",
    "Gloves": "armour",
    "Boots": "armour",
    "Shield": "armour",
    "Quiver": "armour",
    "Focus": "armour",
    "Buckler": "armour",
    "Weapon": "weapon",
}

CACHE_TTL = {
    "currency": 300,
    "unique": 7200,
    "rare": 7200,
    "gem": 7200,
    "default": 7200,
}

PRICE_QUALITY_THRESHOLDS = {
    "default_chaos_min": 1.0,
    "rare_listings_min": 3,
}