import sys
sys.path.insert(0, r'C:\Users\travanx\Dropbox\projects\poe2\ninja')
from data_sources import Poe2ScoutSource
src = Poe2ScoutSource('Runes of Aldur')
refs = src.fetch_reference_currencies()
print('poe2scout ReferenceCurrencies:')
print(f'  1 ex = {refs.get("chaos", "?")} chaos = {refs.get("divine", "?")} divine')
print()
print('Rate check:')
print(f'  1 chaos = {1 / refs["chaos"]:.4f} ex')
print(f'  1 divine = {1 / refs["divine"]:.4f} ex')
print()
print('The user says 1 chaos = 37 ex. Let me see what 36.81 implies:')
print(f'  poe2scout rate: {refs["chaos"]} chaos per ex = {refs["chaos"]:.2f}')
print(f'  That means 1 chaos = 1/{refs["chaos"]:.2f} ex = {1/refs["chaos"]:.4f} ex')
print()
print('User says 1 chaos = 37 ex, which means the rate is 1/37 = 0.027 ex-per-chaos,')
print('or 37 ex-per-chaos. poe2scout says 36.81, so the market is correct.')
print()
print('48 chaos = 48 / 36.81 =', 48 / 36.81, 'ex (using poe2scout rate)')
print('48 chaos in the UI screenshot was probably a seller error,')
print('intended to mean 48x divine or 48x exalts, not literal 48 chaos.')
print()
print('Actually the user said "the seller listed 48 chaos but it should be 1776 ex"')
print('The seller meant: 48 chaos * 37 ex = 1776 ex')
print('But on the actual market, 48 chaos = 1.3 ex')
print('Our code shows 1.3 ex which is the actual market value')
print('User wants to show 1776 ex because that is what the seller intended')

print()
print('Test the actual current trade2 data for our waystone query')
print('The user said the SCREENSHOT shows 48 chaos at the BOTTOM of the list')
print('with the actual market being 5-12 divine per listing.')